// Frontend/microclient-vue/src/App.vue
<template>
  <div style="padding: 2rem;">
    <h1>Vue MicroClient – Produkte</h1>
    <p v-if="products.length === 0">Keine Produkte gefunden.</p>
    <ul v-else>
      <li v-for="p in products" :key="p.id">
        {{ p.name }} – {{ (p.priceCents / 100).toFixed(2) }} €
      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'
const products = ref([])
onMounted(async () => {
  const { data } = await axios.get('/api/products')
  products.value = data
})
</script>

// Frotend/microclient-react/src/App.jsx
import { useEffect, useState } from 'react'
import axios from 'axios'

function App() {
    const [products, setProducts] = useState([])

    useEffect(() => {
        axios.get('/api/products')
            .then(res => setProducts(res.data))
            .catch(console.error)
    }, [])

    return (
        <div style={{ padding: 20 }}>
            <h2>React MicroClient – Produkte</h2>
            {products.length === 0 ? <p>Keine Produkte</p> :
                <ul>{products.map(p => <li key={p.id}>{p.name}</li>)}</ul>}
        </div>
    )
}

export default App
